base:
  testdata:
    filepath_or_buffer: 'datasets/fake_data.csv'
    sep: ','
    header: 0
    names: [ 'userId', 'itemId', 'rating', 'timestamp']
  data:
      filepath_or_buffer: 'datasets/ml-1m/ratings.dat'
      sep: '::'
      header: None
      names: [ 'userId', 'itemId', 'rating', 'timestamp']
  model:
    learning_rate: 0.04
    reg_term: 0.001
    latent_dim: 10
    epochs: 10
